services:
  - type: web
    name: finance-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py collectstatic --noinput && python manage.py migrate && gunicorn config.wsgi:application
